sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t skelcd-control-caasp-image .

script:
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" skelcd-control-caasp-image ./.travis.sh
